version: '3'
services:

  hadoop:
    hostname: hadoop-master
    # image: 'prestodb/cdh5.13-hive:latest'
    image: 'prestodb/hdp2.6-hive:latest'
    container_name: hadoop-master
    volumes:
      - './hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml'
      - './hadoop/lib/json-udf-1.3.8-jar-with-dependencies.jar:/usr/lib/hive/lib/json-udf-1.3.8-jar-with-dependencies.jar'
      - './hadoop/lib/json-serde-1.3.8-jar-with-dependencies.jar:/usr/lib/hive/lib/json-serde-1.3.8-jar-with-dependencies.jar'

  minio:
    hostname: minio
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
    volumes:
      - './minio/data/:/data'
      - './minio/config:/root/.minio'
    environment:
      MINIO_ACCESS_KEY: V42FCGRVMK24JJ8DHUYG
      MINIO_SECRET_KEY: bKhWxVF3kQoLY9kFmt91l+tDrEoZjqnWXzY9Eza
    command: server /data
    
  presto:
    hostname: presto
    image: 'starburstdata/presto:0.203-e.0.1'
    container_name: presto
    ports:
      - '8080:8080'
    volumes: 
      - './presto/minio.properties:/usr/lib/presto/etc/catalog/minio.properties'
      - './hadoop/lib/json-serde-1.3.8-jar-with-dependencies.jar:/usr/lib/presto/lib/plugin/hive-hadoop2/json-serde-1.3.8-jar-with-dependencies.jar'

  polynote:
    hostname: polynote
    image: 'bhavik9243/polynote-spark:latest'
    container_name: polynote
    ports:
      - '8192:8192'
      - '4040:4040'
    volumes:
      - './polynote/data/:/data'
      - './polynote/config:/opt/spark/conf'
      - './polynote/notebooks:/opt/notebooks'
  hue-postgres:
    image: postgres:10
    depends_on:
      - polynote
    container_name: hue-postgres
    restart: always
    environment:
      POSTGRES_DB: hue
      POSTGRES_PASSWORD: hue
      POSTGRES_USER: hue
  hue:
    hostname: hue
    image: 'gethue/hue:latest'
    depends_on:
      - hue-postgres
    container_name: hue
    ports:
      - '8888:8888'
    volumes:
      - ./hue/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini